### ISSUE TITLE
tmpop: reflect the hash of the validation file in the AppHash

### ISSUE THREAD

**Issue by such** [stratumn/sdk#176]
We should make sure there is consensus around the validations that are run by the Tendermint Application. A good way to achieve this is to have the validation file impact the computation of the AppHash.

**Comment by simonvadee** [comment]
POSTULATE: `AppHash` is the root of a merkle tree containing the linkHash of every segment saved in the blockchain since its creation.
For the validation file to have an impact on the AppHash, I can think of: 
(i) inserting the file hash in `segment.link.meta` to change the linkHash
(ii) using `hash(linkHash+validationFileHash)` as a key to store in the merkle tree instead of `linkHash`
(iii) add the file hash as a leaf node in the merkle tree from which the AppHash.

But : 
(i) a segment link is supposed to be immutable, so nope
(ii) one would need to know the validation file (hash) to be able to get a segment from the tree.
(iii) The size of the tree would be (a bit) bigger hence slowing down operations applied to the tree. Furthermore some nodes of the tree would contain keys that are not linkHash, is that a bad thing ?

**Comment by such** [comment]
good analysis thanks.

I think (iii) is completely fine since it will be only one leaf in the tree. The fact that some nodes would not be linkHash is not a big deal either in my opinion.

**Comment by simonvadee** [comment]
- What if a process is added after the genesis block and the validation file has to be updated to include the new process' validation ?
- What if some byzantine node edits his validation file after it was first hashed and included in the tree ?

Every time one validates a segment (or opens the validation file), one could compare the file hash to the one previously inserted in the chain and insert the new hash if it doesn't match.

**Comment by such** [comment]
>- What if a process is added after the genesis block and the validation file has to be updated to include the new process' validation ?

In our vision this is a meta consensus change that needs to be synchronized among all validators. This is why we'd want to include the validation file hash to the AppHash

> - What if some byzantine node edits his validation file after it was first hashed and included in the tree ?

If the byzantin node runs wrong validations we don't really care. He takes the risk of being desynchronized from the blockchain if he accepts a incorrect transaction or reject a correct one.
